var resources = {
	"en": {
        "translation": {
            "locations": "Locations",
            "showlocations": "Show Locations",
            "animals": "Animals",
            "shigi": "Shigi",
            "shigiwolf": "Shigi Wolf",
            "shigiforest": "Shigi Forest",
            "shigiarctic": "Shigi Arctic",
			"bor": "Bor",
			"radbor": "Rad Bor",
			"tokar": "Tokar",
			"tokarblue": "Tokar Blue",
			"tokarparrot": "Tokar Parrot",
			"sasquatch": "Sasquatch",
			"yeti": "Yeti",
			"plants": "Plants",
			"owrong": "Owrong",
			"pitcherplant": "Pitcher Plant",
			"succulentseeds": "Succulent Seeds",
			"items": "Items",
			"itemflint": "Item Flint",
			"itemwood": "Item Wood",
			"lootcrate": "Loot Crate",
			"resources": "Resources",
			"woodlog": "Wood Log",
			"coal": "Coal",
			"limestone": "Limestone/Clay",
			"flint": "Flint/Stone",
			"deadtree": "Dead Tree",
			"ores": "Ores",
			"ironore": "Iron Ore",
			"titranium": "Titranium Ore",
			"mondinium": "Mondinium Ore",
			"ultranium": "Ultranium Ore",
			"largerock": "Large Mining Rock",
			"valley" : "Valley",
			"fortress": "Fortress",
			"transit": "Transit",
			"boonies": "Boonies",
			"crossroad": "Crossroad",
			"airfield": "Airfield",
			"carrier": "Carrier",
			"dome": "Dome",
			"arch": "Arch",
			"created": "Created by:",
			"names": "RogerHN and LuisMika",
			"legal": "Hurtworld and the Hurtworld Logo are trademarks of Bankroll Studios",
			"website": "Hurtworld official website",
			"welcome": "This is the first version of the interactive map.",
			"welcome2": "If you find any bug please post to the",
			"welcome3": "reddit thread.",
			"settings": "Settings",
			"languagechange": "Change Language",
			"translationbr": "Portuguese Brazilian translation by RogerHN",
			"translationru": "Russian translation by Roofy",
			"translationde": "German translation by Valixx",
			"translationcn": "Chinese translation by Smoke6",
			"translationpl": "Polish translation by Magiczna Huśtawka",
			"translationro": "Romanian translation by Blaconix",
			"translationtr": "Turkish translation by Vinerra",
			"translationit": "Italian translation by CHC",
			"translationes": "Spanish traslation by Yoje",
			"version": "Version"
			
        }
    },
  	"br": {
        "translation": {
            "locations": "Locais",
            "showlocations": "Mostrar Locais",
            "animals": "Animais",
            "shigi": "Shigi",
            "shigiwolf": "Shigi Lobo",
            "shigiforest": "Shigi da Floresta",
            "shigiarctic": "Shigi do Ártico",
			"bor": "Javali",
			"radbor": "Javali Radioativo",
			"tokar": "Tokar",
			"tokarblue": "Tokar Azul",
			"tokarparrot": "Tokar Vermelho",
			"sasquatch": "Pé Grande",
			"yeti": "Yeti",
			"plants": "Plantas",
			"owrong": "Owrong",
			"pitcherplant": "Planta de Jarro",
			"succulentseeds": "Sementes Suculentas",
			"items": "Items",
			"itemflint": "Item Sílex",
			"itemwood": "Item Madeira",
			"lootcrate": "Caixa de Loot",
			"resources": "Recursos",
			"woodlog": "Tronco de Madeira",
			"coal": "Carvão",
			"limestone": "Argila/Calcário",
			"flint": "Sílex/Pedra",
			"deadtree": "Árvore Morta",
			"ores": "Minérios",
			"ironore": "Minério de Ferro",
			"titranium": "Minério de Titranium",
			"mondinium": "Minério de Mondinium",
			"ultranium": "Minério de Ultranium",
			"largerock": "Rocha de Mineração",
			"valley" : "Vale",
			"fortress": "Fortaleza",
			"transit": "Trânsito",
			"boonies": "Boonies",
			"crossroad": "Cruzamento",
			"airfield": "Airfield",
			"carrier": "Navio Abandonado",
			"dome": "Dome",
			"arch": "Arco",
			"created": "Criado por:",
			"names": "RogerHN e LuisMika",
			"legal": "Hurtworld e o logo Hurtworld são marcas registradas da Bankroll Studios",
			"website": "Website Oficial do Hurtworld",
			"welcome": "Esta é a primeira versão do mapa interativo.",
			"welcome2": "Se você encontrar algum bug, por favor poste no",
			"welcome3": "tópico do reddit.",
			"settings": "Configurações",
			"languagechange": "Mudar Idioma",
			"translationbr": "Tradução para Português Brasileiro por RogerHN",
			"translationru": "Tradução para Russo por Roofy",
			"translationde": "Tradução para Alemão por Valixx",
			"translationcn": "Tradução para Chinês por Smoke6",
			"translationpl": "Tradução para Polonês por Magiczna Huśtawka",
			"translationro": "Tradução para Romano por Blaconix",
			"translationtr": "Tradução para Turco por Vinerra",
			"translationit": "Tradução para Italiano por CHC",
			"translationes": "Tradução para Espanhol por Yoje",
			"version": "Versão"
        }
    },
	"ru": {
        "translation": {
            "locations": "Локации",
            "showlocations": "Показать локации",
            "animals": "Животные",
            "shigi": "Шиги",
            "shigiwolf": "Дикий Шиги",
            "shigiforest": "Лесной Шиги",
            "shigiarctic": "Арктический Шиги",
			"bor": "Кабан",
			"radbor": "Радиоактивный Кабан",
			"tokar": "Токар",
			"tokarblue": "Синий Токар",
			"tokarparrot": "Токар-попугай",
			"sasquatch": "Снежный",
			"yeti": "Йети",
			"plants": "Растения",
			"owrong": "Апельсин",
			"pitcherplant": "Кувшинка",
			"succulentseeds": "семена Succulent",
			"items": "Вещи",
			"itemflint": "Кремень",
			"itemwood": "Дерево",
			"lootcrate": "Ящик",
			"resources": "Ресурсы",
			"woodlog": "Бревно",
			"coal": "Уголь",
			"limestone": "Известняк/Глина",
			"flint": "Кремень/Камень",
			"deadtree": "Мертвое дерево",
			"ores": "Руды",
			"ironore": "Железная руда",
			"titranium": "Титраниумная руда",
			"mondinium": "Мондиниумная руда",
			"ultranium": "Ультраниумная руда",
			"largerock": "Большой камень",
			"valley" : "Valley",
			"fortress": "Fortress",
			"transit": "Transit",
			"boonies": "Boonies",
			"crossroad": "Crossroad",
			"airfield": "Airfield",
			"carrier": "Carrier",
			"dome": "Dome",
			"arch": "Arch",
			"created": "Создано:",
			"names": "RogerHN и LuisMika",
			"legal": "Hurtworld и логотипы Hurtworld являются тварными знаками Bankroll Studios",
			"website": "Официальный сайт игры",
			"welcome": "Это первая версия карты.",
			"welcome2": "Если вы нашли баг, то пожалуйста пришли его в наш пост на ",
			"welcome3": "Reddit'e или в группу ВК.",
			"settings": "настройки",
			"languagechange": "Изменить язык",
			"translationbr": "Португальский Бразильский перевод RogerHN",
			"translationru": "Перевод на русский от Roofy",
			"translationde": "Перевод на Немецкий от Valixx",
			"translationcn": "Перевод на китайский от Smoke6",
			"translationpl": "Польский перевод от Magiczna Huśtawka",
			"translationro": "Румынский перевод от Blaconix",
			"translationtr": "турецкий перевод от Vinerra",
			"translationit": "Итальянский перевод от CHC",
			"translationes": "Испанский перевод Yoje",
			"version": "версия"
        }
    },
	"de": {
        "translation": {
            "locations": "Standorte",
            "showlocations": "Zeige Standorte",
            "animals": "Tiere",
            "shigi": "Shigi",
            "shigiwolf": "Wolf Shigi",
            "shigiforest": "Wald Shigi",
            "shigiarctic": "Arktis Shigi",
            "bor": "Wildschwein",
            "radbor": "Rad Wildschwein",
            "tokar": "Tokar",
            "tokarblue": "Blauer Tokar",
            "tokarparrot": "Papagei Tokar",
            "sasquatch": "Sasquatch",
            "yeti": "Yeti",
            "plants": "Pflanzen",
            "owrong": "Owrong",
            "pitcherplant": "Kannenpflanze",
            "succulentseeds": "Saftpflanzen",
            "items": "Gegenstände",
            "itemflint": "Feuerstein Gegenstand",
            "itemwood": "Holz Gegenstand",
            "lootcrate": "Beutekiste",
            "resources": "Ressourcen",
            "woodlog": "Holzscheit",
            "coal": "Kohle",
            "limestone": "Kalkstein/Tonerde",
            "flint": "Feuerstein/Stein",
            "deadtree": "Toter Baum",
            "ores": "Erze",
            "ironore": "Eisenerz",
            "titranium": "Titraniumerz",
            "mondinium": "Mondiniumerz",
            "ultranium": "Ultraniumerz",
            "largerock": "Großer Bergbau Fels",
            "valley" : "Tal",
            "fortress": "Festung",
            "transit": "Transit",
            "boonies": "Boonies",
            "crossroad": "Kreuzung",
            "airfield": "Flughafen",
            "carrier": "Flugzeugträger",
            "dome": "Kuppel",
            "arch": "Bogen",
            "created": "Erstellt von:",
            "names": "RogerHN and LuisMika",
            "legal": "Hurtworld and the Hurtworld Logo are trademarks of Bankroll Studios",
            "website": "Offizielle Hurtworld Webseite",
            "welcome": "Dies ist die erste Version der interaktiven Karte.",
            "welcome2": "Wenn ihr irgendwelche Bugs findet, postet sie bitte im",
            "welcome3": "Reddit Forum.",
            "settings": "Einstellungen",
            "languagechange": "Sprache ändern",
            "translationbr": "Portugiesische/Brasilianische Übersetzung von RogerHN",
            "translationru": "Russische Übersetzung von Roofy",
            "translationde": "Deutsche Übersetzung von Valixx",
			"translationcn": "Chinesisch-Übersetzung von Smoke6",
			"translationpl": "Polnische Übersetzung von Magiczna Huśtawka",
			"translationro": "Rumänisch Übersetzung von Blaconix",
			"translationtr": "Türkisch-Übersetzung von Vinerra",
			"translationit": "Italienische Übersetzung durch CHC",
			"translationes": "Spanische Übersetzung von Yoje",
            "version": "version"
        }
    },
	"cn": {
        "translation": {
            "locations": "坐标",
            "showlocations": "显示坐标",
            "animals": "动物",
            "shigi": "兔子",
            "shigiwolf": "红沙漠兔",
            "shigiforest": "鹿",
            "shigiarctic": "雪兔",
            "bor": "猪",
            "radbor": "辐射猪",
            "tokar": "唾沫怪",
            "tokarblue": "雪地唾沫怪",
            "tokarparrot": "红沙漠唾沫怪",
            "sasquatch": "野人",
            "yeti": "雪人",
            "plants": "植物",
            "owrong": "橘子",
            "pitcherplant": "冷冻液",
            "succulentseeds": "防晒霜",
            "items": "物品",
            "itemflint": "小石子",
            "itemwood": "木棍",
            "lootcrate": "地图物资",
            "resources": "资源",
            "woodlog": "圆木",
            "coal": "煤",
            "limestone": "粘土矿",
            "flint": "燧石矿",
            "deadtree": "枯树",
            "ores": "矿石",
            "ironore": "铁矿",
            "titranium": "红矿",
            "mondinium": "绿矿",
            "ultranium": "篮矿",
            "largerock": "大矿石",
            "valley" : "峡谷",
            "fortress": "风车集装箱",
            "transit": "雪山2号集装箱",
            "boonies": "雪山1号集装箱",
            "crossroad": "红沙漠1号集装箱",
            "airfield": "红沙漠2号集装箱",
            "carrier": "航母",
            "dome": "大铁球",
            "arch": "石拱门",
            "created": "建立者:",
            "names": "RogerHN and LuisMika",
            "legal": "Hurtworld以及Hurtworld商标归属于 Bankroll Studios",
            "website": "Hurtworld 官方网站",
            "welcome": "这是hurtworld交互地图第一版.",
            "welcome2": "如果你发现任何bug，请反馈至",
            "welcome3": "reddit 板块.",
            "settings": "设置",
            "languagechange": "更改语言",
            "translationbr": "葡萄牙语、巴西语 翻译者：RogerHN",
            "translationru": "俄罗斯语 翻译者： Roofy",
			"translationde": "的德文译本 Valixx",
			"translationcn": "中文 翻译者：百度贴吧zcdxj",
			"translationpl": "波兰语翻译 Magiczna Huśtawka!",
			"translationro": "波兰语翻译 Blaconix",
			"translationtr": "土耳其语翻译 Vinerra",
			"translationit": "意大利语翻译 CHC",
			"translationes": "西班牙语翻译 Yoje",
			
            "version": "版本"
        }
    },
	"pl": {
        "translation": {
            "locations": "Lokacje",
            "showlocations": "Pokaż Lokacje",
            "animals": "Zwierzęta",
            "shigi": "Shigi",
            "shigiwolf": "Wilczy Shigi",
            "shigiforest": "Leśny Shigi",
            "shigiarctic": "Arktyczny Shigi",
            "bor": "Dzik",
            "radbor": "Napromieniowany dzik",
            "tokar": "Tokar",
            "tokarblue": "Niebieski Tokar",
            "tokarparrot": "Tokar Parrot",
            "sasquatch": "Sasquatch",
            "yeti": "Yeti",
            "plants": "Rośliny",
            "owrong": "Owrong",
            "pitcherplant": "Dzbanecznik",
            "succulentseeds": "Kaktus",
            "items": "Przedmioty",
            "itemflint": "Kamień",
            "itemwood": "Drewno",
            "lootcrate": "Skrzynki",
            "resources": "Surowce",
            "woodlog": "Kłody",
            "coal": "Węgiel",
            "limestone": "Glina/Wapień",
            "flint": "Krzemień/Kamień",
            "deadtree": "Kłody",
            "ores": "Rudy",
            "ironore": "Ruda żelaza",
            "titranium": "Ruda Titranium",
            "mondinium": "Ruda Mondinium",
            "ultranium": "Ruda Ultranium",
            "largerock": "Duża skała",
            "valley" : "Dolina",
            "fortress": "Twierdza",
            "transit": "Przejście",
            "boonies": "Zadupie",
            "crossroad": "Skrzyżowanie",
            "airfield": "Lotnisko",
            "carrier": "Lotniskowiec",
            "dome": "Kopuła",
            "arch": "Łuk",
            "created": "Stworzona przez:",
            "names": "RogerHN i LuisMika",
            "legal": "Hurtworld i logo Hurtworld są marką Bankroll Studios",
            "website": "Strona oficjalna Hurtworld",
            "welcome": "To pierwsza wersja interaktywnej mapy.",
            "welcome2": "Jeśli znajdziesz jakieś błedy, zgłoś je",
            "welcome3": "w temacie na reddit.",
            "settings": "Ustawienia",
            "languagechange": "Zmień język",
            "translationbr": "Portugalski brazylijski Tłumaczenie przez RogerHN",
            "translationru": "Tłumaczenie rosyjskie przez Roofy",
			"translationde": "Tłumaczenie Niemiecki Valixx",
			"translationcn": "Tłumaczenie na chiński przez Smoke6",
			"translationpl": "Przekład polski Magiczna Huśtawka",
			"translationro": "Tłumaczenie Rumuński przez Blaconix",
			"translationtr": "Tłumaczenie Turecki przez Vinerra",
			"translationit": "Tłumaczenie włoskiego CHC",
			"translationes": "Tłumaczenie Hiszpański Yoje",
            "version": "version 2.0",
		}
	},
	"ro": {
		"translation": {
			"locations": "Locații",
			"showlocations": "Arată locațiile",
			"animals": "Animale", "shigi": "Shigi",
			"shigiwolf": " Lup Shigi",
			"shigiforest": "Shigi de Pădure",
			"shigiarctic": "Shigi Arctic",
			"bor": "Bor",
			"radbor": "Bor Radiat",
			"tokar": "Tokar",
			"tokarblue": "Tokar Albastru",
			"tokarparrot": "Tokar Papagal",
			"sasquatch": "Sasquatch",
			"yeti": "Yeti",
			"plants": "Plante",
			"owrong": "Owrong",
			"pitcherplant": "Planta Pitcher",
			"succulentseeds": "Semințe Succulent",
			"items": "Iteme",
			"itemflint": "Flint",
			"itemwood": "Lemn",
			"lootcrate": "Ladă cu Loot",
			"resources": "Resurse",
			"woodlog": "Buștean",
			"coal": "Cărbune",
			"limestone": "Calcar/Lut",
			"flint": "Flint/Piatră",
			"deadtree": "Copaci Putrezi",
			"ores": "Minereuri",
			"ironore": "Minereu de Fier",
			"titranium": "Minereu de Titranium",
			"mondinium": "Minereu de Mondinium",
			"ultranium": "Minereu de Ultranium",
			"largerock": "Stâncă de minereuri",
			"valley" : "Vale",
			"fortress": "Fortăreața",
			"transit": "Tranzit",
			"boonies": "Văgăuna",
			"crossroad": "Intersecție",
			"airfield": "Aeroport",
			"carrier": "Portavion",
			"dome": "Observatoriu",
			"arch": "Arc",
			"created": "Făcută de:",
			"names": "RogerHN și LuisMika",
			"legal": "Hurtworld și logo-ul Hurtworld sunt mărci înregistrate ale Bankroll Studios",
			"website": "Site oficial Hurtworld",
			"welcome": "Aceasta e prima versiune a hărtii interactive.",
			"welcome2": "Dacă găsești vreun bug te rog postează",
			"welcome3": "pe thread-ul de pe reddit.",
			"settings": "Setări",
			"languagechange": "Schimbă Limba",
			"translationbr": "Traducere în Portugueză Braziliană făcută de RogerHN",
			"translationru": "Traducere în Russian făcută de Roofy",
			"translationde": "Traducere în German făcută de Valixx",
			"translationcn": "Traducere în Chinese făcută de Smoke6",
			"translationpl": "Traducere în Polish făcută de Magiczna Huśtawka",
			"translationro": "Traducere în Română făcută de Blaconix",
			"translationtr": "Traducere în Turcă de Vinerra",
			"translationit": "Traducere italiană de CHC",
			"translationes": "Traducere spaniolă de Yoje",
			"version": "Versiunea",
		}
	},
	"tr": {
		"translation": {
			"locations": "Konumlar",
			"showlocations": "Konumları göster",
			"animals": "Hayvanlar",
			"shigi": "Shigi",
			"shigiwolf": "Kurt Shigi",
			"shigiforest": "Orman Shigi'si",
			"shigiarctic": "Kutup Shigi'si",
			"bor": "Domuz",
			"radbor": "Radyasyonlu Domuz",
			"tokar": "Tokar",
			"tokarblue": "Mavi Tokar",
			"tokarparrot": "Papağan Tokar",
			"sasquatch": "Koca Ayak",
			"yeti": "Yeti",
			"plants": "Bitkiler",
			"owrong": "Portakal",
			"pitcherplant": "İbrik Otu",
			"succulentseeds": "Etli Tohumlar",
			"items": "Eşyalar",
			"itemflint": "Çakmak Taşı Eşyası",
			"itemwood": "Odun Eşyası",
			"lootcrate": "Eşya Sandığı",
			"resources": "Kaynaklar",
			"woodlog": "Tahta Kütük",
			"coal": "Kömür",
			"limestone": "Kireçtaşı/Kil",
			"flint": "Çakmaktaşı/Taş",
			"deadtree": "Ölü Ağaç",
			"ores": "Madenler",
			"ironore": "Demir Madeni",
			"titranium": "Titranium Madeni",
			"mondinium": "Mondinium Madeni",
			"ultranium": "Ultranium Madeni",
			"largerock": "Büyük Madeni Kaya",
			"valley" : "Vadi",
			"fortress": "Kale",
			"transit": "Yol Geçişi",
			"boonies": "Boonies",
			"crossroad": "Kavşak",
			"airfield": "Havaalanı",
			"carrier": "Uçak Gemisi",
			"dome": "Kubbe",
			"arch": "Kemer",
			"created": "Oluşturan:",
			"names": "RogerHN ve LuisMika",
			"legal": "Hurtworld ve Hurtworld Logosu Bankroll Studios'un markalarıdır.",
			"website": "Hurtworld resmi websitesi",
			"welcome": "Bu, interaktif haritanın ilk versiyonudur.",
			"welcome2": "Eger herhangi bir bug bulursanız buraya yazınız",
			"welcome3": "reddit konusu.",
			"settings": "Ayarlar",
			"languagechange": "Dili Değiştir",
			"translationbr": "Portekizce Brezilya RogerHN tarafından çevrilmiştir",
			"translationru": "Rusça Roofy tarafından çevrilmiştir",
			"translationde": "Almanca Valixx tarafından çevrilmiştir",
			"translationcn": "Çince Smoke6 tarafından çevrilmiştir",
			"translationpl": "Lehçe Magiczna Huśtawka tarafından çevrilmiştir",
			"translationro": "Rumence Blaconix tarafından çevrilmiştir",
			"translationtr": "Türkçe Vinerra tarafından çevrilmiştir",
			"translationit": "Tarafından İtalyanca çevirisi CHC",
			"translationes": "Traduzione Español di Yoje",
			"version": "Versiyon",
		}
	},
	"it" : {
		"translation" : {
			"locations": "Luoghi",
			"showlocations": "Mostra luoghi",
			"animals": "Animali",
			"shigi": "Shigi",
			"shigiwolf": "Shigi Lupo",
			"shigiforest": "Shigi Forestale",
			"shigiarctic": "Shigi Artico",
			"bor": "Bor",
			"radbor": "Bor Radiattivo",
			"tokar": "Tokar",
			"tokarblue": "Tokar Blu",
			"tokarparrot": "Tokar Rosso",
			"sasquatch": "Sasquatch",
			"yeti": "Yeti",
			"plants": "Piante",
			"owrong": "Owrong",
			"pitcherplant": "Piante carnivore",
			"succulentseeds": "Piante grasse",
			"items": "Oggetti",
			"itemflint": "Selce",
			"itemwood": "Bastoni",
			"lootcrate": "Casse",
			"resources": "Risorse",
			"woodlog": "Tronchi",
			"coal": "Carbone",
			"limestone": "Calce/Argilla",
			"flint": "Selce/Pietra",
			"deadtree": "Alberi morti",
			"ores": "Minerali",
			"ironore": "Minerali di ferro",
			"titranium": "Minerali di Titanio",
			"mondinium": "Minerali di Modio",
			"ultranium": "Minerali di Ultranio",
			"largerock": "Grandi rocce ",
			"valley": "Valle",
			"fortress": "Fortezza",
			"transit": "Stazione di transito",
			"boonies": "Sobborgo",
			"crossroad": "Incrocio",
			"airfield": "Aeroporto",
			"carrier": "Portaerei",
			"dome": "Cupola",
			"arch": "Arco",
			"created": "Creato da:",
			"names": "RogerHN e LuisMika",
			"legal": "Hurtworld e il Logo Hurtworld sono marchio di fabbrica della Bankroll Studios",
			"website": "Sito ufficiale di Hurtworld",
			"welcome": "Questa è la prima versione della mappa interattiva.",
			"welcome2": "Se trovi un bug per favore segnalalo su",
			"welcome3": "Reddit.",
			"settings": "Impostazioni",
			"languagechange": "Cambia lingua",
			"translationbr": "Traduzione Portoghese Brasiliano di RogerHN",
			"translationru": "Traduzione Russo di Roofy",
			"translationde": "Traduzione Tedesco di Valixx",
			"translationcn": "Traduzione Cinese di Smoke6",
			"translationpl": "Traduzione Polacco di Magiczna Huśtawka",
			"translationro": "Traduzione Rumeno di Blaconix",
			"translationtr": "Traduzione Turco di Vinerra",
			"translationit": "Traduzione di CHC",
			"translationes": "Traduzione Español di Yoje",
			"version": "Versione",
		}
	},
	"es" : {
		"translation" : {
			"locations": "Locación",
			"showlocations": "Mostrar Locación",
			"animals": "Animales",
			"shigi": "Shigi",
			"shigiwolf": "Lobo Shigi",
			"shigiforest": "Shigi de Bosque",
			"shigiarctic": "Shigi Arctico",
			"bor": "Bor",
			"radbor": "Bor Radiactivo",
			"tokar": "Tokar",
			"tokarblue": "Tokar Azul",
			"tokarparrot": "Tokar Zanahoria",
			"sasquatch": "Sasquatch",
			"yeti": "Yeti",
			"plants": "Plantas",
			"owrong": "Owrong",
			"pitcherplant": "Planta Lanzadora",
			"succulentseeds": "Semillas Suculentas",
			"items": "Objetos",
			"itemflint": "Objeto Pedernal",
			"itemwood": "Obejeto Madera",
			"lootcrate": "Cajón de botín",
			"resources": "Recursos",
			"woodlog": "Tronco de Madera",
			"coal": "Carbón",
			"limestone": "Caliza/Arsilla",
			"flint": "Pedernal/Piedra",
			"deadtree": "Arból Muerto",
			"ores": "Minerales",
			"ironore": "Mineral de oro",
			"titranium": "Mineral de Titranio",
			"mondinium": "Mineral e Mondinio",
			"ultranium": "Mineral de Ultranio",
			"largerock": "Roca de minar grande",
			"valley": "Valle",
			"fortress": "Fuerte",
			"transit": "Transito",
			"boonies": "Campo",
			"crossroad": "Cruce",
			"airfield": "AeroPuerto",
			"carrier": "Portaaviones",
			"dome": "Domo",
			"arch": "Arco",
			"created": "Creado Por:",
			"names": "RogerHN y LuisMika",
			"legal": "Hurtworld y the Hurtworld Logo son marcas Bankroll Studios",
			"website": "Sitio Oficial de Hurtworld",
			"welcome": "Esta es la primera version del mapa interactivo.",
			"welcome2": "Si encuentras algún bug por favor reportalo",
			"welcome3": "Hilo de reddit.",
			"settings": "Ajustes",
			"languagechange": "Cambiar Lenguaje",
			"translationbr": "Traducción Portuguesa por RogerHN",
			"translationru": "Traducción Rusa por Roofy",
			"translationde": "Traducción Alemana por Valixx",
			"translationcn": "Traducción China por Smoke6",
			"translationpl": "Traducción Polaca por Huśtawka",
			"translationro": "Traducción Rumana por Blaconix",
			"translationtr": "Traducción Turca por Turca Vinerra",
			"translationit": "Traducción italiana de CHC",
			"translationes": "Traducción Español por Yoje",
			"version": "Versión",
		}
	},	
};

$(document).ready(function() {
	var language = "en";
	if (localStorage.getItem("language") != null)
		language = localStorage.getItem("language");
	
    i18n.init({
        lng: language,
        resStore: resources,
        fallbackLng: "en"
    }, function(o) {
        $(document).i18n()
    }), $(".lang").click(function() {
        var o = $(this).attr("data-lang");
		
		localStorage.setItem("language", o);
		
        i18n.init({
            lng: o
        }, function(o) {
            $(document).i18n()
        })
    })
});